// motion-engine.js
// Finalized inference pipeline for Qualcomm FOMM ONNX assets.

export const IO_CONFIG = {
  // Corrected tensor names to match QAI Hub v0.49.1 FOMM models
  kpDetector: {
    inputName: "image",
    outputKeypoints: "keypoints",
    outputJacobian: "jacobian", 
  },
  generator: {
    inputSource: "source_image",
    inputKpSource: "source_keypoints",
    inputKpDriving: "driving_keypoints",
    inputJacobianSource: "source_jacobian",
    inputJacobianDriving: "driving_jacobian",
    output: "image",
  },
  frameSize: 256,
};

let kpSession = null;
let genSession = null;

export function configureOrt() {
  ort.env.wasm.numThreads = navigator.hardwareConcurrency || 4;
  ort.env.wasm.simd = true;
}

/**
 * Pre-flight check: Verify files exist before ORT tries to load them.
 */
async function verifyFile(url) {
    const response = await fetch(url, { method: 'HEAD' });
    if (!response.ok) throw new Error(`File not found: ${url} (${response.status})`);
    return true;
}

/**
 * Loads sessions via URL strings.
 */
export async function loadSessions(kpModelUrl, genModelUrl, executionProviders = ["wasm"]) {
  // 1. Verify availability first to debug 404s
  await verifyFile(kpModelUrl);
  await verifyFile(genModelUrl);
  
  // Extract expected external data internal identifiers and target URLs
  const kpDataFileName = kpModelUrl.split('/').pop().replace('.onnx', '.data');
  const genDataFileName = genModelUrl.split('/').pop().replace('.onnx', '.data');

  const kpDataUrl = kpModelUrl.replace('.onnx', '.data');
  const genDataUrl = genModelUrl.replace('.onnx', '.data');

  // Verify external weight data files are available before ORT loads
  await verifyFile(kpDataUrl);
  await verifyFile(genDataUrl);

  // 2. Create sessions with externalData configured to prevent Emscripten FileSystem mount errors
  kpSession = await ort.InferenceSession.create(kpModelUrl, { 
    executionProviders,
    externalData: [
      { path: kpDataFileName, data: kpDataUrl }
    ]
  });
  
  genSession = await ort.InferenceSession.create(genModelUrl, { 
    executionProviders,
    externalData: [
      { path: genDataFileName, data: genDataUrl }
    ]
  });

  // Debug: Log the loaded layers
  console.log("Detector Inputs:", kpSession.inputNames);
  console.log("Generator Inputs:", genSession.inputNames);
  
  return { kpSession, genSession };
}

export function isLoaded() {
  return !!(kpSession && genSession);
}

export function frameToTensor(canvas, size = IO_CONFIG.frameSize) {
  const off = document.createElement("canvas");
  off.width = size;
  off.height = size;
  const ctx = off.getContext("2d");
  ctx.drawImage(canvas, 0, 0, size, size);
  
  const { data } = ctx.getImageData(0, 0, size, size);

  const floatData = new Float32Array(3 * size * size);
  for (let i = 0; i < size * size; i++) {
    floatData[i] = data[i * 4] / 255;
    floatData[size * size + i] = data[i * 4 + 1] / 255;
    floatData[2 * size * size + i] = data[i * 4 + 2] / 255;
  }
  return new ort.Tensor("float32", floatData, [1, 3, size, size]);
}

export function tensorToImageData(tensor, size = IO_CONFIG.frameSize) {
  const data = tensor.data;
  const out = new Uint8ClampedArray(size * size * 4);
  for (let i = 0; i < size * size; i++) {
    out[i * 4] = clamp255(data[i] * 255);
    out[i * 4 + 1] = clamp255(data[size * size + i] * 255);
    out[i * 4 + 2] = clamp255(data[2 * size * size + i] * 255);
    out[i * 4 + 3] = 255;
  }
  return new ImageData(out, size, size);
}

function clamp255(v) { return Math.max(0, Math.min(255, v)); }

async function detectKeypoints(frameTensor) {
  const feeds = { [IO_CONFIG.kpDetector.inputName]: frameTensor };
  const results = await kpSession.run(feeds);
  const kp = results[IO_CONFIG.kpDetector.outputKeypoints];
  const jac = results[IO_CONFIG.kpDetector.outputJacobian] || null;
  
  if (!kp) {
      console.error("Available tensors in KP:", Object.keys(results));
      throw new Error(`Missing tensor: ${IO_CONFIG.kpDetector.outputKeypoints}`);
  }
  return { kp, jac };
}

export async function runFrame(sourceTensor, sourceKp, sourceJac, drivingFrameTensor) {
  if (!isLoaded()) throw new Error("Models not loaded yet.");
  
  const { kp: drivingKp, jac: drivingJac } = await detectKeypoints(drivingFrameTensor);
  
  const feeds = {
    [IO_CONFIG.generator.inputSource]: sourceTensor,
    [IO_CONFIG.generator.inputKpSource]: sourceKp,
    [IO_CONFIG.generator.inputKpDriving]: drivingKp,
  };

  // Only append Jacobian tensors to feeds if they were actually generated by the detector.
  // Passing null to genSession.run() causes a crash.
  if (sourceJac) {
      feeds[IO_CONFIG.generator.inputJacobianSource] = sourceJac;
  }
  if (drivingJac) {
      feeds[IO_CONFIG.generator.inputJacobianDriving] = drivingJac;
  }

  const results = await genSession.run(feeds);
  const out = results[IO_CONFIG.generator.output];
  if (!out) {
      console.error("Available tensors in Generator:", Object.keys(results));
      throw new Error(`Missing output tensor: ${IO_CONFIG.generator.output}`);
  }
  return out;
}

export async function computeSourceKeypoints(sourceTensor) {
  return detectKeypoints(sourceTensor);
}
